// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2JCBloUdqNNE2LcDRkdmwDEEPHEF-c4',
    appId: '1:437589353894:web:7227b6c915002a93051b67',
    messagingSenderId: '437589353894',
    projectId: 'greenbooks-9cff5',
    authDomain: 'greenbooks-9cff5.firebaseapp.com',
    storageBucket: 'greenbooks-9cff5.firebasestorage.app',
    measurementId: 'G-RVE55J802S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZm-D72aq6v1qEpt31slt56ah5da5Xajk',
    appId: '1:437589353894:android:9c61008049eb4447051b67',
    messagingSenderId: '437589353894',
    projectId: 'greenbooks-9cff5',
    storageBucket: 'greenbooks-9cff5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZak7kH5K_V6YyRokU51iSB07jNar8qXM',
    appId: '1:437589353894:ios:e2728ba9773a1305051b67',
    messagingSenderId: '437589353894',
    projectId: 'greenbooks-9cff5',
    storageBucket: 'greenbooks-9cff5.firebasestorage.app',
    iosBundleId: 'com.example.greenbooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZak7kH5K_V6YyRokU51iSB07jNar8qXM',
    appId: '1:437589353894:ios:e2728ba9773a1305051b67',
    messagingSenderId: '437589353894',
    projectId: 'greenbooks-9cff5',
    storageBucket: 'greenbooks-9cff5.firebasestorage.app',
    iosBundleId: 'com.example.greenbooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa2JCBloUdqNNE2LcDRkdmwDEEPHEF-c4',
    appId: '1:437589353894:web:a8721a136d779916051b67',
    messagingSenderId: '437589353894',
    projectId: 'greenbooks-9cff5',
    authDomain: 'greenbooks-9cff5.firebaseapp.com',
    storageBucket: 'greenbooks-9cff5.firebasestorage.app',
    measurementId: 'G-8F5YP0RXBV',
  );

}